version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/djangoproject
    ports:
      - 8010:8010
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8010
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db